version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
  
  client:
    build:
      context: ./client
    ports:
      - "3001:3001"
    stdin_open: true
   
    depends_on:
      - server
    links:
      - server